import {chromium,expect} from '../frontend/node_modules/@playwright/test/index.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';
const out=path.resolve(process.argv[2]);
const seed=JSON.parse(await fs.readFile(path.join(out,'seed.json'),'utf8'));
const checks=[],errors=[];
const api=async(url,method='GET',body)=>{
  const r=await fetch(seed.base+'/api'+url,{method,headers:{Authorization:'Bearer '+seed.token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
  if(!r.ok)throw Error(await r.text());return r.json();
};
const record=name=>{checks.push({name,passed:true});console.log(name);};
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--disable-gpu','--disable-gpu-compositing']});
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));
try {
  await page.goto(seed.base+'/#token='+seed.token);
  await page.getByLabel('选择文档',{exact:true}).selectOption(seed.document);
  const tree=page.getByRole('region',{name:'文档与页面',exact:true});
  await tree.getByRole('button',{name:/第 1 页/}).first().click();
  await page.getByRole('tab',{name:'结构复核',exact:true}).click();
  const review=page.getByRole('region',{name:'结构建议与复核',exact:true});
  await expect(review.getByLabel('结构建议',{exact:true})).toBeVisible();
  await expect(review.getByRole('table',{name:'当前结构',exact:true})).toContainText('Revenue');
  await expect(review.getByRole('table',{name:'候选结构',exact:true})).toContainText('-0.01');
  const queue=page.getByRole('region',{name:'文档复核队列',exact:true});
  expect((await api(`/documents/${seed.document}/review-queue`)).total).toBe(2);
  record('document queue groups whole-table and local insertion alternatives into one task per table');
  await review.scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(out,'01-structure-comparison.png'),fullPage:true,animations:'disabled'});
  await page.getByRole('tab',{name:/^表格/}).click();
  await page.getByRole('textbox',{name:'第 2 行第 2 列',exact:true}).fill('001.05');
  await page.getByRole('tab',{name:'结构复核',exact:true}).click();
  await review.getByRole('button',{name:'检查已有候选',exact:true}).click();
  await expect(review.getByRole('table',{name:'候选结构',exact:true})).toContainText('001.05');
  await review.getByRole('button',{name:'接受结构建议',exact:true}).click();
  await page.getByRole('tab',{name:/^表格/}).click();
  await expect(page.getByRole('textbox',{name:'第 3 行第 2 列',exact:true})).toHaveValue('-0.01');
  await expect(page.getByRole('textbox',{name:'第 2 行第 2 列',exact:true})).toHaveValue('001.05');
  record('manual amount survives candidate adoption and missing row has literal source text');
  await page.getByRole('button',{name:'撤销',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'第 3 行第 2 列',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'重做',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'第 3 行第 2 列',exact:true})).toHaveValue('-0.01');
  record('structure adoption shares durable editor undo and redo');
  await queue.getByRole('button',{name:/第 2 页/}).click();
  await expect.poll(async()=>page.getByLabel('当前识别结果',{exact:true}).inputValue()).toBe(seed.pages[1].result);
  await review.getByRole('button',{name:'暂缓',exact:true}).click();
  const views=await api(`/results/${seed.pages[1].result}/structure`);
  expect(views.proposals.some(p=>p.state==='deferred')).toBe(true);
  await review.getByRole('button',{name:'保留当前结构',exact:true}).click();
  await expect.poll(async()=>(await api(`/documents/${seed.document}/review-queue`)).tasks.filter(t=>t.kind==='structure').length).toBe(0);
  record('cross-page navigation, deferral and keep-current decisions persist');
  await page.reload();
  await tree.getByRole('button',{name:/第 1 页/}).first().click();
  await page.getByRole('tab',{name:/^表格/}).click();
  await expect(page.getByRole('textbox',{name:'第 3 行第 2 列',exact:true})).toHaveValue('-0.01');
  const result=await api(`/results/${seed.pages[0].result}`);
  expect(result.edited.tables[0].cells.at(-1).structure_source.token_ids).toEqual(['p1-token-2-1']);
  record('reload restores adopted revision and source token IDs');
  await page.setViewportSize({width:1280,height:800});
  await page.getByRole('tab',{name:'结构复核',exact:true}).click();
  await review.scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(out,'02-small-laptop.png'),fullPage:true,animations:'disabled'});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const timing=await api(`/documents/${seed.document}/review-queue`);
  expect(timing.timing.events).toBeGreaterThan(0);
  expect(timing.timing.human_efficiency_claim).toBe(false);
  record('small-laptop viewport has no horizontal document overflow and timing is not a human efficiency claim');
  expect(errors).toEqual([]);
} catch(e) { errors.push(e.stack || String(e)); process.exitCode=1; }
finally {
  await browser.close();
  await fs.writeFile(path.join(out,'report.json'),JSON.stringify({passed:errors.length===0,checks,errors,scope:seed.scope,browser_closed:true},null,2));
}
